site_name: Página MkDocs

nav:
        - Primera página:
            Primera página.md
            
        - Segunda página:
            Segunda página.md

        - Tercera página:
            Tercera página.md

theme: readthedocs
